version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/themes/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
