baseURL = "https://github.zshell.dev"
languageCode = "en"
title = "❮ Z-Shell ZI ❯"
theme = "github-style"
googleAnalytics = "G-4R9S46N2LB"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
author = "Z-Shell Community"
description = "A Swiss army knife for Zsh"
#  github = "z-shell"
#  facebook = ""
#  twitter = "zshell_zi"
#  linkedin = "ss-o"
#  instagram = ""
#  tumblr = ""
email = "team@zshell.dev"
url = "https://github.zshell.dev"
keywords = "zsh, github, toolchain"
rss = true
lastmod = true
userStatusEmoji = ""
favicon = "images/avatar.png"
location = "United Kingdom"
enableGitalk = false

[params.gitalk]
# clientID = ""
# clientSecret = ""
# repo = "github.zshell.dev"
# owner = "z-shell"
# admin = "ss-o"
# id = "location.pathname"
# labels = "gitalk"
# perPage = 15
# pagerDirection = "last"
# createIssueManually = false
# distractionFreeMode = false
[[params.links]]
title = "Z-Shell"
href = "https://github.com/z-shell"
icon = "https://github.com/z-shell.png"
[[params.links]]
title = "digital-clouds"
href = "https://github.com/digital-clouds"
icon = "https://github.com/digital-clouds.png"
#[[params.links]]
#title = "ss-o"
#href = "https://github,com/ss-o"
#icon = "https://github.com/ss-o.png"

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]
